import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { jost } from "./fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <div className="flex  flex-col   md:overflow-hidden  ">
      <div className="w-full flex-none ">
        <Navbar />
      </div>
    {children}
    </div></body>
    </html>
  );
}
